# Vagrant.configure("2") do |config|
#   config.vm.box = "generic/rocky9"
# end

BOX_IMAGE = "generic/ubuntu2204"
HOST_ID = ""# This should be manually changed per system
NODE_COUNT = 2 # This should be manually changed per system

Vagrant.configure("2") do |config|
  # Skip auto update
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "NODE-v#{HOST_ID}0#{i}", autostart: false do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "NODE-V#{HOST_ID}0#{i}"

      # DEV ONLY - USE PUBLIC FOR PRODUCTION
      # config.vm.network "private_network",
      #   ip: "192.168.10#{HOST_ID}.10#{i}"
    end
  end

  # Enable access from public network
  config.vm.network "public_network",
    bridge: "eno1",
    use_dhcp_assigned_default_route: true

  ##########################################################
  # READ SETUP_VAGRANT_HOST.SH FOR REFERENCE
  ##########################################################
  # Uncomment if VM should have more than 40GB default size
  # config.vagrant.plugins = "vagrant-disksize"
  # config.disksize.size = '512GB'

  # VM reource allocation
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  # Synced folder
  # config.vm.synced_folder "/mnt/config/", "/home/vagrant/config",
  #   create: true

  # Guest machine configuration

   config.vm.provision "ansible" do |ansible|
     ansible.become = true
     ansible.compatibility_mode = "2.0"
     ansible.verbose = "v"
     ansible.playbook = "playbook.yml"
   end

end

