apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-pv-claim
  namespace: docker-registry
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_share
    server: nfs.local.lan
  persistentVolumeReclaimPolicy: Retain
