apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      registry:
        port: 5000
        exposed: true
        exposedPort: 5000
    additionalArguments:
      - "--entryPoints.registry.address=:5000/tcp"

